readmeio/metrics-sdks

packages/ruby/spec/readme/har_request_spec.rb
This allows us to build up full http request doubles, without having to
specify values we don't care about.
Note that if overriding the `url` property to add query parameters, you
should also set the `query_params` property as the factory method
doesn't do any logic to keep these two in sync.
This whole PR is all testing 😆
=> Extract test helper factory for http requests

packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/readme/metrics_spec.rb
This commit adds some additional validation around options. The new
validations verify the types of arguments being passed in.
Automated tests were added testing each initialization option
=> Add additional option validation

packages/ruby/lib/readme/har/response_serializer.rb, packages/ruby/spec/readme/har/response_serializer_spec.rb
Some responses have no response body (e.g. an HTTP 204 response).
`Rack::Response` handles this by returning `nil` when calling `#body`.
The HAR spec mentions that `response.content.text` key is optional.
However, it _does_ require the `response.content.mimeType` key. Based on
discussion with the Readme.io team, we decided to send an empty string in
this spot when there is no request body.
The HAR spec is ambiguous about the `response.content.size` key. It
mentions that it should be 0 for 304 responses (another scenario with no
body) and -1 if unknown. I chose to set 0 for responses without a body
since we do know the length and the spec specifically says to use 0
in some instances of no-body responses.
While testing this code, I found a bug where attempting to read the body
more than …
=> Add support for empty response bodies

packages/ruby/spec/readme/metrics_spec.rb
We are building an app stack with multiple middlewares in several
places and lots of unrelated configuration options. I extracted a
factory function to clean things up in the tests.
This is a test-only change
=> Extract app builder function

packages/ruby/README.md
This updates the example code in the README is better reflect how a user might use this middleware with a warden-based authentication scheme.
No behavior was changed in this commit.
=> Update README with more accurate Warden example

.github/workflows/php.yml, packages/php/composer.json
Laravel 8 hit today, so we need to add it into our allowable install list.
Thankfully it doesn't seem like anything there will impact us https://laravel.com/docs/8.x/upgrade
=> feat: running php sdk tests against laravel 8

.github/MAINTAINERS.md, packages/python/building.md
Adds a new maintainers guide detailing how to handle our SDK release process.
=> docs: adding a maintainers guide for publishing releases

packages/python/setup.py
- Updating Python SDK version to 1.0.6
- [PyPi release](https://pypi.org/project/readme-metrics/)
=> chore(setup.py): updating version to 1.0.6

.github/workflows/codeql-analysis.yml
Thoughts on adding this workflow?
=> add code scanning workflow

packages/ruby/spec/readme/metrics_spec.rb
Thought they were fixed, but I guess it's hard to tell with flakey tests... This should do the trick 🤞
=> test(ruby): fix flakey tests

packages/ruby/lib/readme/metrics/version.rb
=> chore(ruby): bump to v1.1.0

.github/MAINTAINERS.md
=> docs(ruby): add docs to publish ruby gem

package-lock.json, packages/node/.eslintignore, packages/node/.eslintrc.js, packages/node/__tests__/index.test.ts, packages/node/__tests__/lib/construct-payload.test.ts, packages/node/__tests__/lib/object-to-array.test.ts, packages/node/__tests__/lib/process-request.test.ts, packages/node/__tests__/lib/process-response.test.ts, packages/node/package-lock.json, packages/node/package.json, packages/node/src/lib/construct-payload.ts, packages/node/src/lib/express-middleware.ts, packages/node/src/lib/metrics-log.ts, packages/node/src/lib/object-to-array.ts, packages/node/src/lib/process-request.ts, packages/node/src/lib/process-response.ts
=> chore(deps-dev): upgrading eslint and @readme/eslint-config

.github/workflows/php.yml, packages/php/composer.json, packages/php/psalm.xml, packages/php/src/Metrics.php
Updated three packages to ensure it works with Laravel 9
The github workflow will test Laravel 9, but you can test this locally by following these instructions: https://laravel.com/docs/9.x/installation and adding a file reference to this project like this: https://getcomposer.org/doc/05-repositories.md#path
=> fix(php): update http, support and package-versions to ensure this can run with laravel 9

package-lock.json, packages/node/package.json
I saw [this pr](https://github.com/readmeio/metrics-sdks/pull/433) to bump body-parser but I dont think we're using this dep anywhere.
If tests pass then we're good ✅
=> refactor(node): remove unused body-parser dep

.github/workflows/nodejs.yml, __tests__/integrations/node.Dockerfile, docker-compose.yml, packages/node/.eslintrc.js, packages/node/examples/express/index.js, packages/node/examples/hapi/README.md, packages/node/examples/hapi/index.js, packages/node/examples/hapi/package-lock.json, packages/node/examples/hapi/package.json
| 🚥 Fix RM-XXX |
| :-- |
Add example hapi add to integration test suite
Based off of Gabe's hapi demo here: https://gist.github.com/gratcliff/f20c32505a24d7d687461a1d3075ea76
Does the build pass? ✅
=> feat(examples): add hapi example to integration test suite

.github/workflows/python.yml, __tests__/integration.test.js, __tests__/integrations/python.Dockerfile, docker-compose.yml, packages/python/examples/flask/app.py, packages/python/examples/flask/requirements.txt, packages/python/readme_metrics/PayloadBuilder.py, packages/python/readme_metrics/flask_readme.py, packages/python/readme_metrics/publisher.py, packages/python/readme_metrics/tests/PayloadBuilder_test.py, packages/python/readme_metrics/tests/flask_test.py, packages/python/requirements.txt
Bring over changes from #479 
Add python to the languages that have proper integration testing servers
Additional fixes for python sdk:
- ensure we're generating a uuid
- ensure `response.content.size` is a number
Added some more integration tests:
- make sure the date is in the correct format
- check for `development` being a proper boolean
=> Datetime and development_mode boolean fixes - Flask - Python

packages/php/composer.json
https://github.com/readmeio/metrics-sdks/runs/7200715627?check_suite_focus=true
PHP builds should be passing.
=> ci: fixing composer installs in CI

.github/workflows/cloudflare-worker.yml, package-lock.json, packages/cloudflare-worker/package-lock.json, packages/cloudflare-worker/package.json, packages/cloudflare-worker/src/index.js
=> fix: various fixes to the cloudflare worker

__tests__/integration-metrics.test.js, __tests__/integration-webhooks.test.js, packages/python/examples/README.md, packages/python/examples/flask/app.py, packages/python/examples/flask/webhook.py, packages/python/readme_metrics/VerifyWebhook.py
Follow on from here: #526 but with cleaner history, and cherry-picked commits.
Still to do:
=> feat(python): add python webhook integration test (take 2)

__tests__/integration-metrics.test.js, __tests__/integration-webhooks.test.js, packages/dotnet/examples/net6.0-webhook/Program.cs, packages/sdk-snippets/src/helpers/code-converter.test.ts, packages/sdk-snippets/src/helpers/code-converter.ts, packages/sdk-snippets/src/targets/__snapshots__/targets.test.ts.snap, packages/sdk-snippets/src/targets/dotnet/net6.0/webhooks/client.ts, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/client.ts, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/fixtures/empty-default.cs, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/fixtures/empty.cs, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/fixtures/security-and-server-variables.cs, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/fixtures/security-types.cs, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/fixtures/security-variables.cs, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/fixtures/server-variables.cs, packages/sdk-snippets/src/targets/dotnet/target.ts, packages/sdk-snippets/src/targets/node/express/webhooks/client.ts, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/empty-default.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/empty.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-and-server-variables.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-types.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-variables.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/server-variables.js, packages/sdk-snippets/src/targets/node/target.ts, packages/sdk-snippets/src/targets/targets.test.ts, packages/sdk-snippets/src/targets/targets.ts
Added updated express snippets and .net snippet
=> feat(sdk-snippets): add .net and updated express webhooks snippets

packages/sdk-snippets/src/targets/__snapshots__/targets.test.ts.snap, packages/sdk-snippets/src/targets/python/flask/webhooks/client.ts, packages/sdk-snippets/src/targets/python/flask/webhooks/fixtures/empty-default.py, packages/sdk-snippets/src/targets/python/flask/webhooks/fixtures/empty.py, packages/sdk-snippets/src/targets/python/flask/webhooks/fixtures/security-and-server-variables.py, packages/sdk-snippets/src/targets/python/flask/webhooks/fixtures/security-types.py, packages/sdk-snippets/src/targets/python/flask/webhooks/fixtures/security-variables.py, packages/sdk-snippets/src/targets/python/flask/webhooks/fixtures/server-variables.py, packages/sdk-snippets/src/targets/python/target.ts, packages/sdk-snippets/src/targets/targets.ts
=> feat(snippets): python webhook snippets

packages/sdk-snippets/src/helpers/code-builder.ts, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/client.ts, packages/sdk-snippets/src/targets/node/express/webhooks/client.ts, packages/sdk-snippets/src/targets/php/laravel/webhooks/client.ts, packages/sdk-snippets/src/targets/python/flask/webhooks/client.ts
This refactors our `CodeBuilder.variable()` method into being a `pushVariable()`. Hopefully the resulting work here is a little easier to grok.
=> refactor: cleaning up how we're adding variables into snippets

.github/workflows/python.yml, docker-compose.yml
Forgot to wire up python webhook to gh actions
Do the tests pass? ✅ 
Do the tests contain the python webhook integration test? ✅
=> chore(integration): forgot to wire up python webhook to gh actions

packages/ruby/examples/metrics-rails/app/controllers/metrics_controller.rb, packages/sdk-snippets/src/targets/__snapshots__/targets.test.ts.snap, packages/sdk-snippets/src/targets/ruby/rails/webhooks/client.ts, packages/sdk-snippets/src/targets/ruby/rails/webhooks/fixtures/empty-default.rb, packages/sdk-snippets/src/targets/ruby/rails/webhooks/fixtures/empty.rb, packages/sdk-snippets/src/targets/ruby/rails/webhooks/fixtures/quirky-escaping.rb, packages/sdk-snippets/src/targets/ruby/rails/webhooks/fixtures/security-and-server-variables.rb, packages/sdk-snippets/src/targets/ruby/rails/webhooks/fixtures/security-types.rb, packages/sdk-snippets/src/targets/ruby/rails/webhooks/fixtures/security-variables.rb, packages/sdk-snippets/src/targets/ruby/rails/webhooks/fixtures/server-variables.rb, packages/sdk-snippets/src/targets/ruby/target.ts, packages/sdk-snippets/src/targets/targets.test.ts, packages/sdk-snippets/src/targets/targets.ts
Added Ruby/rails webhooks code snippet
=> feat: ruby sdk snippet

packages/sdk-snippets/README.md, packages/sdk-snippets/src/targets/node/express/webhooks/client.ts, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/empty-default.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/empty.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/quirky-escaping.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-and-server-variables.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-types.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-variables.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/server-variables.js
| 🚥 Fix RM-5469 |
| :-- |
A follow-up to #602 that feels a little cleaner 😭 sorry!
Do you like this better?
=> fix: another rewrite

docs/cloudflare-workers.md, docs/dotnet-setup.md, docs/nodejs-setup.md, docs/php-laravel-setup.md, docs/python-django-setup.md, docs/python-flask-setup.md, docs/python-wsgi-setup.md, docs/ruby-setup.md, packages/node/examples/fastify/index.js
=> docs: node v6 updates and general documentation cleanup

docs/aws-webhook.md
Will be published to here upon merging into `main`: https://docs.readme.com/main/docs/amazon-api-gateway-webhook
=> docs: API gateway personalized docs webhook

docs/aws-webhook.md
Ray wrote this and Sarah/I signed off on this already, but let me know what you think!
=> docs: refresh language on AWS webhook

docs/cloudflare-workers.md, docs/php-laravel-setup.md, docs/python-django-setup.md, docs/python-flask-setup.md, docs/python-wsgi-setup.md, packages/node/src/config/index.js, packages/node/test/lib/process-request.test.ts, packages/php/examples/laravel/config/readme.php, packages/php/src/Metrics.php, packages/php/src/config.dist.php
| 🚥 Fixes ISSUE_ID |
Fixes up our base URL in our SDKs (and our docs) to correctly point to dash.readme.com
Do tests pass?
=> fix: use correct API base URL

packages/python/examples/flask/webhooks.py, packages/python/readme_metrics/VerifyWebhook.py, packages/ruby/Gemfile.lock, packages/ruby/examples/metrics-rails/Gemfile.lock
| 🚥 Fixes #785 |
Fixes from #785 plus the original fix from #664 with the integration test properly updated to expose the issue and more closely match what we're showing in the SDK snippets code. See this comment for more info:
https://github.com/readmeio/metrics-sdks/pull/785#issuecomment-1506704433
=> fix(python): webhook code sample broken

packages/python/examples/metrics_django/README.md
| 🚥 Fixes n/a |
| :----------- |
- Fix link to CONTRIBUTING.md
- none
=> fix link to CONTRIBUTING.md

packages/python/.pylintrc, packages/python/readme_metrics/PayloadBuilder.py, packages/python/readme_metrics/VerifyWebhook.py, packages/python/readme_metrics/publisher.py
| 🚥 Fixes #849 |
| :------------ |
- fix: raise more specific exceptions
- fix: re-enable broad exception warning
**don't commit this yet**
This changes the API surface in a minor but also important way, so it should probably required at least a minor version bump? Is it worth it, and how would I do that if so?
=> Raise narrower exceptions

packages/node/src/lib/setup-readme-view.ts
=> style: setup view

packages/ruby/Gemfile.lock, packages/ruby/lib/readme/http_request.rb, packages/ruby/lib/readme/mask.rb, packages/ruby/lib/readme/metrics/version.rb, packages/ruby/spec/readme/http_request_spec.rb, packages/ruby/spec/readme/payload_spec.rb
=> chore: release 2.4.0 Ruby Gem

packages/node/src/lib/ReadMe.ts, packages/node/test/index.test.ts, packages/node/test/lib/construct-payload.test.ts, packages/node/test/lib/get-group-id.test.ts, packages/node/test/lib/process-request.test.ts, packages/node/test/lib/verify-webhook.test.ts, packages/node/test/tsconfig.json
Noticed a bunch of type errors when running `npx tsc -p test/` from the `packages/node` directory. Not sure if we should do this typechecking in CI?
Do you notice any errors when running `npx tsc -p test/` from the `packages/node` directory?
=> fix: type errors in tests

packages/ruby/Gemfile.lock
fix ruby lint error due to bundle version
=> fix(ruby): update bundle version

packages/python/readme_metrics/__init__.py
Version bump to 3.3.0 of our managed package
=> chore(python): updates __init__.py to 3.3.0

packages/python/readme_metrics/__init__.py
Describe in detail what this PR is for.
Bump package version for Python to 3.4.0
=> chore(python): updates __init__.py to 3.4.0

packages/java/examples/SpringMetricsExample/pom.xml, packages/java/examples/SpringMetricsExample/src/main/java/com/owl/example/CustomUserDataCollectorConfig.java, packages/java/examples/SpringMetricsExample/src/main/java/com/owl/example/OwlController.java, packages/java/metrics-core/pom.xml, packages/java/metrics-core/src/main/java/com/readme/core/dataextraction/LogOptions.java, packages/java/metrics-core/src/main/java/com/readme/core/dataextraction/payload/PayloadData.java, packages/java/metrics-core/src/main/java/com/readme/core/dataextraction/payload/requestresponse/BaseRequestResponseData.java, packages/java/metrics-core/src/main/java/com/readme/core/dataextraction/payload/requestresponse/RequestData.java, packages/java/metrics-core/src/main/java/com/readme/core/dataextraction/payload/requestresponse/ResponseData.java, packages/java/metrics-core/src/main/java/com/readme/core/datatransfer/HttpDataSender.java, packages/java/metrics-core/src/main/java/com/readme/core/datatransfer/OutgoingLogBodyConstructor.java, packages/java/metrics-core/src/test/java/com/readme/core/datatransfer/OutgoingLogBodyConstructorTest.java, packages/java/metrics-spring/pom.xml, packages/java/metrics-spring/src/main/java/com/readme/spring/config/DataCollectionAutoConfiguration.java, packages/java/metrics-spring/src/main/java/com/readme/spring/datacollection/DataCollectionFilter.java, packages/java/metrics-spring/src/main/java/com/readme/spring/datacollection/ServletDataPayloadAdapter.java, packages/java/metrics-spring/src/test/java/com/readme/spring/datacollection/DataCollectionFilterTest.java, packages/java/metrics-spring2/pom.xml, packages/java/metrics-spring2/src/main/java/com/readme/spring/config/DataCollectionAutoConfiguration.java, packages/java/metrics-spring2/src/main/java/com/readme/spring/datacollection/DataCollectionFilter.java, packages/java/metrics-spring2/src/main/java/com/readme/spring/datacollection/ServletDataPayloadAdapter.java, packages/java/metrics-spring2/src/test/java/com/readme/spring/datacollection/DataCollectionFilterTest.java
- Fixed bugs due to description of: https://github.com/readmeio/metrics-sdks/issues/1248
- Updated test
=> fix: Fixed Java SDK bugs after QA testing
