packages/node/__tests__/index.test.js, packages/node/config/default.json, packages/node/index.js
> Previously started on as https://github.com/readmeio/readme-node/pull/7 but pulled over here to be completed.
This resolves a race condition where our buffer doesn't always get cleaned out after logs are attempted to be sent.
=> fix: issue where the same logs would get sent multiple times

README.md, packages/node/README.md, packages/node/__tests__/index.test.js, packages/node/config/default.json, packages/node/config/localhost.json, packages/node/index.js, packages/node/package-lock.json, packages/node/package.json, packages/php/README.md, packages/php/composer.json, packages/php/src/Metrics.php, packages/php/src/Middleware.php, packages/php/src/config.dist.php, packages/php/tests/ConfigTest.php, packages/php/tests/MetricsTest.php
> 🚧  &nbsp; This work is dependent upon https://github.com/readmeio/readme/pull/2844 getting into production as that change updates the `baseUrl` property in `GET /api/v1` to support projects with custom domains.
This reworks the new `x-readme-log` header for returning the metrics log UUID to the client into a new `x-documentation-url` header that returns a fully-formed URL to view that log on the Developer Metrics page for the requesting ReadMe project.
Since this URL isn't something that the Metrics API has access to, we need to first make an API request to the ReadMe API `GET /api/v1` to retrieve the `baseUrl` for the project that is being set up with Metrics. As we don't want to make this request for every single Metrics call, we're caching to a local file. 
Along with storing the …
=> feat: reworking `x-readme-log` into `x-documentation-url`

packages/node/__tests__/index.test.js, packages/node/index.js
Since [this commit](https://github.com/readmeio/metrics-sdks/pull/15/commits/50ebe66c43048ea9990ccce3ed7dcd7d9f3e7d50), the Metrics API will 400 when receiving new logs. This has been happening since our migration away from `request` to the `node-fetch` library for our external API requests. The `node-fetch` library [requires that we set a  `Content-Type` header when sending JSON POST bodies](https://www.npmjs.com/package/node-fetch#post-with-json).
Also, per discussion with @erunion, this PR also adds `User-Agent` headers for requests to the ReadMe and ReadMe Metrics APIs.
=> fix: add content-type and user-agent headers

packages/node/__tests__/index.test.js, packages/node/index.js
Noticed this earlier when we had some high response times from our API and `null` was dumped into the `x-documentation-url` header, resulting in ReadMe API responses that looked like
```json
{
"error": "APIKEY_NOTFOUND",
"message": "We couldn't find your API key",
"suggestion": "The API key you passed in (T3d······················To=) doesn't match any keys we have in our system. API keys must be passed in as the username part of basic auth. You can get your API key in Configuration > API Key, or in the docs.",
"docs": "null/logs/<uuid>",
"help": "If you need help, email support@readme.io and include the following link to your API log: 'null/logs/<uuid>'.",
"poem": [
"The ancient gatekeeper declares:",
"'To pass, reveal your API key'",
"'T3dsZ…', you start to ramble",
"Oops, you …
```
=> fix: prevent potentially null base log urls from being used

packages/ruby/Gemfile, packages/ruby/Gemfile.lock, packages/ruby/README.md, packages/ruby/lib/readme/metrics.rb, packages/ruby/lib/readme/metrics/version.rb, packages/ruby/readme-metrics.gemspec, packages/ruby/spec/readme/metrics_spec.rb
This creates a simple middleware that logs requests received to the
given logging API endpoint in the format: `"GET http://example.com"`.
The actual Readme.io payload format is more complicated than this. We
will add support for it in a follow-up commit.
There is an **automated test** using `Rspec` and `Rack::Test`. We also tested **manually** with a simple Rack application that acts as both the client API and the Readme API:
```ruby
$LOAD_PATH << File.expand_path("../path/to/metrics-sdks/packages/ruby/lib", __FILE__)
class ApiApp
def call(env)
puts "=== API ==="
end
end
class ReadmeApp
def call(env)
puts "=== README ==="
puts env['rack.input'].read
end
end
map "/readme" do |builder|
run ReadmeApp.new
end
map "/api" do
use …
```
=> Create simple HTTP-logging middleware

packages/ruby/Gemfile, packages/ruby/Gemfile.lock, packages/ruby/README.md, packages/ruby/lib/data.json, packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/readme/metrics_spec.rb, packages/ruby/spec/schema/afterRequest.json, packages/ruby/spec/schema/beforeRequest.json, packages/ruby/spec/schema/browser.json, packages/ruby/spec/schema/cache.json, packages/ruby/spec/schema/content.json, packages/ruby/spec/schema/cookie.json, packages/ruby/spec/schema/creator.json, packages/ruby/spec/schema/entry.json, packages/ruby/spec/schema/har.json, packages/ruby/spec/schema/header.json, packages/ruby/spec/schema/log.json, packages/ruby/spec/schema/page.json, packages/ruby/spec/schema/pageTimings.json, packages/ruby/spec/schema/postData.json, packages/ruby/spec/schema/query.json, packages/ruby/spec/schema/readmeGroup.json, packages/ruby/spec/schema/readmeMetrics.json, packages/ruby/spec/schema/request.json, packages/ruby/spec/schema/response.json, packages/ruby/spec/schema/timings.json
This sends a valid hardcoded payload (in the form of the `data.json` file)
to the Readme API with all the proper headers and authentication.
The middleware now takes an API key during initialization and no longer
needs an endpoint which has become a constant.
The hard-coded data we wrote is valid according to [HAR
1.2](http://www.softwareishard.com/blog/har-12-spec). We noticed that
there are some required fields from the spec that are neither mentioned
by the API nor used in the nodejs implementation. We decided to include
them for validity sake and at some point the backend might want to fully
support the HAR 1.2 spec.
The added fields are:
* `entries.cache`
* `entries.timing`
* `entries[].request.cookies`
* `entries[].request.headerSize`
* `entries[].request.bodySize`
* …
=> Send valid payloads to Readme API

packages/ruby/lib/readme/har.rb, packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/fixtures/har.json, packages/ruby/spec/readme/har_spec.rb, packages/ruby/spec/readme/metrics_spec.rb, packages/ruby/spec/readme/payload_spec.rb
Previously, we were using hard-coded values for the HAR. Now we correctly derive a HAR from the Rack env (request) and response.
The HAR spec was designed to describe requests made from a client so there are some keys that are nonsensical in the context of a middleware.
We added a bunch of automated tests around the HAR generation. Currently only for the happy path of a POST request with a JSON payload.
For manual testing, run the folllowing rack app:
```ruby
$LOAD_PATH << File.expand_path("../path/to/metrics-sdks/packages/ruby/lib", __FILE__)
class ApiApp
def call(env)
end
end
map "/api" do
use Readme::Metrics, "YOUR_API_KEY_HERE"
run ApiApp.new
end
```
with
```
rackup
```
make a request:
```
curl 'http://localhost:9292/api/foo?id=1&name=joel' …
```
=> Generate real HAR from request and response

packages/ruby/README.md, packages/ruby/lib/readme/metrics.rb, packages/ruby/lib/readme/payload.rb, packages/ruby/spec/readme/metrics_spec.rb, packages/ruby/spec/readme/payload_spec.rb
This commit adds a new block argument to the middleware which, given the environment, can fetch user info. The result is passed into the `Metrics::Payload` and added to the payload sent out to the ReadMe API.
With a small example app, I was able to pass in a block with some hardcoded values:
```ruby
class ApiApp
def call(env)
end
end
map "/api" do
use Readme::Metrics, "API_KEY" do |env|
{id: "anthonym", label: "Anthony M.", email: "anthony@example.com"}
end
run ApiApp.new
end
```
Which successfully posted the data:
`curl 'http://localhost:9292/api/foo?id=1&name=joel' -H "X-Custom: my custom header" -H "Content-Type: application/json" -X POST -d '{"key": "value"}'` …
=> Gather user info for calls to ReadMe API

packages/ruby/README.md, packages/ruby/lib/readme/metrics.rb, packages/ruby/lib/readme/payload.rb, packages/ruby/spec/readme/metrics_spec.rb, packages/ruby/spec/readme/payload_spec.rb
This commit allows users to set whether or not requests will be flagged as development data or not.
We used a small example application and set `development: false` . This application successfully posted non-development data to the dashboard:
`curl 'http://localhost:9292/api/foo?id=1&name=joel' -H "X-Custom: my custom header" -H "Content-Type: application/json" -X POST -d '{"key": "value"}'`
```ruby
class ApiApp
def call(env)
end
end
map "/api" do
options = {api_key: "lyBlA1eaaKUXFoxQDbJ9FX2B5VajBAHA", development: false} 
use Readme::Metrics, options do |env|
{id: "anthonym", label: "Anthony M.", email: "anthony@example.com"}
end
run ApiApp.new
end
```
=> Set development flag in middleware configuration

packages/ruby/lib/readme/har.rb, packages/ruby/lib/readme/har_request.rb, packages/ruby/spec/fixtures/har_request.json, packages/ruby/spec/readme/har_request_spec.rb, packages/ruby/spec/readme/har_spec.rb
This pulls out all the request logic from `Har` to its own object so
it's easier to test variations.
This is a pure refactor, there are no behavior changes. New automated unit tests were added around some existing behavior.
=> Extract `HarRequest` object

packages/ruby/lib/http_request.rb, packages/ruby/lib/readme/har.rb, packages/ruby/lib/readme/har_request.rb, packages/ruby/spec/http_request_spec.rb, packages/ruby/spec/readme/har_request_spec.rb, packages/ruby/spec/readme/har_spec.rb
`Rack::Request` provides some niceties over a raw env hash but is still
missing some key behavior such as getting HTTP headers or safely reading
the body.
This extracts an object to that wraps `Rack::Request` and provides a
nice interface for these things. Some of the methods just delegate to
existing `Rack::Request` functionality. I made the decision not to try
and isolate the two in testing in order to get more readable tests.
This is a pure refactor with no behavior changes. Additional automated unit tests were added around newly public behavior.
=> Extract `HttpRequest` object

packages/ruby/README.md, packages/ruby/lib/readme/har.rb, packages/ruby/lib/readme/har_request.rb, packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/readme/har_request_spec.rb, packages/ruby/spec/readme/har_spec.rb
This commit allows an optional list of parameters to be filtered to be passed in when configuring the middleware. The argument is an array of string. Values in the `filter_params` array filter the body and headers of both request and response
We tested this manually using the sample rack application:
`curl 'http://localhost:9292/api/foo?id=1&name=joel' -H "X-Filtered: my custom header" -H "Content-Type: application/json" -X POST -d '{"key": "value", "filtered": "filtered"}'`
```ruby
class ApiApp
def call(env)
end
end
map "/api" do
options = {
api_key: "API_KEY",
development: false,
filter_params: ["filtered", "X-Filtered"]
}
use Readme::Metrics, options do |env|
{id: …
```
=> Allow user to set attribute names to filter

packages/ruby/README.md, packages/ruby/lib/readme/filter.rb, packages/ruby/lib/readme/har.rb, packages/ruby/lib/readme/har_collection.rb, packages/ruby/lib/readme/har_request.rb, packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/readme/filter_spec.rb, packages/ruby/spec/readme/har_collection_spec.rb, packages/ruby/spec/readme/har_request_spec.rb, packages/ruby/spec/readme/har_spec.rb
This commit expands the ability to users to specify a list of keys that should only be sent up to the metrics API. A new filter class was introduced to wrap the `filter_params` and new `allow_only` values and provide the appropriate filter function given the values.
A `HarCollection` wrapper class was also introduced that filters and formats the given hash.
Using the following curl command and sample app, we confirmed that the application will only send values matching the given list in the headers, query params and bodies. 
`curl 'http://localhost:9292/api/foo?id=1&name=joel' -H "X-Filtered: my custom header" -H "Content-Type: application/json" -X POST -d '{"key": "value", "dont_filter": "not filtered"}`
```ruby
$LOAD_PATH << File.expand_path("../../metrics-sdks/packages/ruby/lib", …
```
=> Allow users to specify a set of values that should only be sent to the API

packages/ruby/lib/readme/har_request.rb, packages/ruby/spec/readme/har_request_spec.rb, packages/ruby/spec/readme/metrics_spec.rb
When a POST request has no body, don't include the `postBody` key in the
HAR payload. We distinguish between "no body" and empty
text/json/xml/whatever by checking for the presence of the
`Content-Type` header.
Create a sample API like:
```ruby
$LOAD_PATH << File.expand_path("../path/to/metrics-sdks/packages/ruby/lib", __FILE__)
class ApiApp
def call(env)
[200, {"Content-Length" => "2"}, ["Ok"]]
end
end
map "/api" do
use Readme::Metrics, api_key: "YOUR_API_KEY" do
{ id: 1, label: "Joël", email: "user@example.com" }
end
run ApiApp.new
end
```
and boot it with:
```
rackup
```
Then make a cURL POST request without a body:
```
$ curl 'http://localhost:9292/api/foo'  -H 'Content-Length: 0' -X POST
```
The request should show up in the Readme.io dashboard
=> Allow empty POST bodies

packages/ruby/README.md, packages/ruby/lib/readme/metrics.rb, packages/ruby/lib/readme/payload.rb, packages/ruby/lib/readme/request_queue.rb, packages/ruby/spec/readme/metrics_spec.rb, packages/ruby/spec/readme/payload_spec.rb, packages/ruby/spec/readme/request_queue_spec.rb, packages/ruby/spec/schema/payload.json
This commit adds simple request batching behavior to the middleware.
Previously, each request made to an application using this middleware
would cause a new request to be sent to the ReadMe API. A new
`RequestQueue` object was introduced to collect requests and provide a
batched response to send out when ready.
The batch size can be controlled by the user using the `buffer_length`
option. It defaults to 10.
Both unit and integrations tests were added to cover the new functionality.
Using the following sample application and curl request, we confirmed that middleware appropriately batches the requests.
`curl 'http://localhost:9292/api/foo?id=1&name=joel' -H "X-Filtered: my custom header" -H "Content-Type: application/json" -X POST -d '{"key": "value", "dont_filter": "not filtered"}'` …
=> Batch API requests to ReadMe

packages/ruby/lib/readme/har/response_serializer.rb, packages/ruby/lib/readme/har/serializer.rb, packages/ruby/spec/fixtures/har_response.json, packages/ruby/spec/readme/har/response_serializer_spec.rb, packages/ruby/spec/readme/har/serializer_spec.rb
We want to handle several variations of serialization with bodies for
HAR. Extracting an standalone object for this allows us to handle all
that logic in one place while making unit testing variants easy.
This is a pure refactor, with some added unit tests. No behavior changed here.
=> Extract HAR body serializer

packages/ruby/lib/readme/errors.rb, packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/readme/metrics_spec.rb
This commit adds some validation around user info block required by the
middleware.
One check runs at application boot and ensures that the block is not
nil.
The other checks occur at run time and ensure that if the block is not
configured properly, the application will not crash and log an error
instead. The request to the Readme API will be aborted and the response
will be passed on through the rest of the middleware stack.
The new checks are covered by the automated test suite.
```ruby
class ApiApp
def call(env)
[200, {"Content-Length" => "2"}, ["Ok"]]
end
end
map "/api" do
options = {api_key: "API_KEY"}
use Readme::Metrics, options
run ApiApp.new
end
```
``` …
```
=> Validate user info block configuration

packages/ruby/spec/readme/metrics_spec.rb
Early on, we discovered that code broke for some HTTP verbs, notably
GET. However, new features added since then have inadvertantly fixed the
causes of these issues.
This commit adds tests to show that the app can indeed handle the most
common HTTP verbs:
* GET
* POST
* PUT
* PATCH
* DELETE
Indeed, no code changes were needed as the middleware can correctly
handle all of these.
This PR is all tests
=> Test that we can handle multiple HTTP verbs

packages/ruby/lib/http_request.rb, packages/ruby/lib/readme/har/request_serializer.rb, packages/ruby/spec/http_request_spec.rb, packages/ruby/spec/readme/har/request_serializer_spec.rb, packages/ruby/spec/readme/metrics_spec.rb
According to HAR, data submitted with `multipart/form-data` or
`application/x-www-form-urlencoded` MIME types should be formatted as
key-value pairs under a `request.postData.params` key rather than the
`request.postData.text` key we use for other request types like JSON.
Additionally, we want to parse the data and filter out keys based on the
user's preferences.
Create a sample Rack app like:
```ruby
$LOAD_PATH << File.expand_path("../path/to/metrics-sdks/packages/ruby/lib", __FILE__)
class ApiApp
def call(env)
[200, {"Content-Length" => "2"}, ["Ok"]]
end
end
map "/api" do
use Readme::Metrics, reject_params: ["reject"], buffer_length: 1, api_key: "YOUR_KEY_HERE" do
{ id: 1, label: "Joël", email: "user@example.com" }
end
run ApiApp.new
end
```
run it via:
```
$ …
```
=> Add support for form data

packages/ruby/lib/readme/har/response_serializer.rb, packages/ruby/spec/readme/har/response_serializer_spec.rb
This commit expands the content type check in the
Har::ResponseSerializer to accept multiple JSON mime types.
Using the following sample application:
```ruby
class ApiApp
def call(env)
[
200,
{"Content-Length" => "20", "Content-Type" => "application/x-json"},
[{response: "value"}.to_json]
]
end
end
map "/api" do
options = {
api_key: "api_key",
buffer_length: 1
}
use Readme::Metrics, options do |env|
{id: "anthonym", label: "Anthony M.", email: "anthony@example.com"}
end
run ApiApp.new
end
```
And the following curl command:
`curl 'http://username:password@localhost:9292/api/foo' -X POST`
A request was successfully added to the metrics dashboard with a newly added json mime type. …
=> Support multiple JSON mime types

packages/ruby/lib/readme/metrics.rb, packages/ruby/lib/readme/request_queue.rb, packages/ruby/spec/readme/metrics_spec.rb, packages/ruby/spec/readme/request_queue_spec.rb
This commit updates the behavior of the middleware to perform
non-blocking requests to the ReadMe API. When the request queue is full,
the request to ReadMe is performed in a new thread. The application's
response is passed through straight away.
In tests that make API requests, we had to stub the `Thread` class to ensure tests are run
synchronously and deterministically.
On Mac OS you can install the Network Link Conditioner to simulate slow network conditions:
https://developer.apple.com/download/more/?name=network%20link
1. Throttle network speed
2. Boot up a rack app with metrics middleware configured
3. Make some requests to the middleware
4. The rack app should response instantly despite the slow network
5. The request to readme should take some time to complete due to slow network …
=> Perform API request to ReadMe in a new thread

packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/readme/metrics_spec.rb
This commit wraps the processing of the request and response in a
rescue block. This ensures that if any of the processing we're doing
inside the middleware fails unexpectedly, the application will continue
to work.
An automated test was added for the new method that wraps the response/request processing.
=> Ensure any failures inside middleware don't crash application

packages/ruby/lib/http_request.rb, packages/ruby/lib/readme/har/serializer.rb, packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/http_request_spec.rb, packages/ruby/spec/readme/har/serializer_spec.rb, packages/ruby/spec/readme/metrics_spec.rb
This commit updates the behavior of the middleware to skip processing
OPTIONS requests.
A new test was added to the test suite to ensure a request is not made to the ReadMe API. This was also tested manually using a rack application and this curl command:
`curl -i -X OPTIONS localhost:9292/api`
No corresponding item shows up in the dashboard.
=> Don't send request on OPTIONS

packages/ruby/lib/content_type_helper.rb, packages/ruby/lib/http_request.rb, packages/ruby/lib/http_response.rb, packages/ruby/lib/readme/filter.rb, packages/ruby/lib/readme/har/response_serializer.rb, packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/content_type_helper_spec.rb, packages/ruby/spec/readme/filter_spec.rb, packages/ruby/spec/readme/har/response_serializer_spec.rb, packages/ruby/spec/readme/metrics_spec.rb
When given `allow_only` or `reject` parameters, we want to make sure
that the request and response bodies are properly filtered. In order to
do that, we need to be able to parse them. Currently we only support
parsing JSON and form-encoded bodies. If bodies come in as other content
types _and_ a filter is configured, we should not submit the request to
the Readme API because it might contain sensitive data.
If no filter is set, it is safe to just pass-through any bodies to the
Readme API regardless of content type.
Testing this behavior was rather annoying as I had to create new
instances of both app and middleware for each test in order to get
custom response bodies and middleware configurations desired. To make
this nicer I ended up creating a bunch of testing helpers. I also
created …
=> Don't submit non-filterable bodies

packages/ruby/README.md, packages/ruby/lib/http_response.rb, packages/ruby/lib/readme/har/response_serializer.rb, packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/http_response_spec.rb, packages/ruby/spec/readme/har/response_serializer_spec.rb
The Content-Length header is not included by default starting in Rails
5. This commit adds some new functionality to the HttpResponse class
so that we can calculate the content length if the header is not present.
Commit that removes the middleware: https://github.com/rails/rails/commit/56903585a099ab67a7acfaaef0a02db8fe80c450
Automated tests were added to cover this new behavior.
=> Provide default values when Content-Length is absent

packages/ruby/lib/readme/har/request_serializer.rb, packages/ruby/spec/readme/har/request_serializer_spec.rb
While `Metrics` checks that requests have the right content-type for the
filters in place, it is possible for requests to lie about their
content.
If the filter is a "pass-through", then we don't care about the
content type. In fact, we don't want to parse it even if it is JSON
because we'd just be turning it back into a string.
On the other hand, if we can't successfully parse JSON for a
non-"pass-through" filter, we let it raise. The most likely thing that
has happened is that either the request has lied about it having JSON
content or the JSON being submitted is malformed. Either way, this is
catastrophic as we have no way of filtering out sensitive parameters.
`Metrics` has a top-level rescue that will catch this error and cleanly
abort the attempt to log the request to Readme.io.
To …
=> Don't pass-through requests that fail to parse

packages/ruby/lib/readme/metrics.rb
When something goes wrong in the middleware, we rescue and just return
to the next middleware in the chain.
This commit adds some logging in that case so that users can better
understand why some requests aren't being submitted to the ReadMe API.
This might be due to a bug in this middleware (in which case this error
will allow users to create better bug reports), or it might be due to a
malformed body (in which case surfacing that to the user is helpful).
Create a rack app and set up the readme middleware with an allow/reject parameter config. Then make a request that has a content type of `application/json` but whose body is not JSON:
```
curl 'http://localhost:9292/api/foo' -X POST -d "not json" -H 'Content-Type: application/json'
```
Check your logs, you should see an error informing …
=> Log an error if we abort the request to ReadMe

.github/workflows/php.yml, packages/php/composer.json, packages/php/src/Metrics.php, packages/php/tests/MetricsTest.php
Updates the PHP SDK to be able to support Guzzle 7, dropping Guzzle 6 in the process.
=> fix: updating the php sdk to support guzzle 7

packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/readme/metrics_spec.rb
If the request or response body is empty, we don't  need to filter it so
it's OK do do a pass-through regardless of the content-type.
Create a rack app that returns an empty body, configure it with a reject parameter, and try to make a request to it. Expect to see the request show up in the Readme dashboard.
=> Submit empty bodies even with filters

packages/ruby/lib/readme/filter.rb, packages/ruby/spec/readme/filter_spec.rb
HTTP headers are not case-sensitive so they might show up differently
that the user expected when setting up allow-only or reject parameters.
If a user configures `reject_params: ["authorization"]`, we want to
reject the HTTP `Authorization` header no matter what case it comes in
as.
Configure a rack app with `reject_params: ["authorization"]`, then make a request to the app with an `Authorization` header. Expect to see the request show up in the Readme dashboard without the header.
```
curl http://localhost:9292/api/foo -H 'Authorization: Basic U2luYXRyYSBVc2VyOkFQSV9LRVk='
```
=> Filter parameters case-insensitively

packages/ruby/lib/http_request.rb, packages/ruby/spec/http_request_spec.rb
Previously, we were submitting all the Rack env values prefixed with
`HTTP_` as headers to the Readme API. However, per the [Rack
spec](https://github.com/rack/rack/blob/master/SPEC.rdoc),
`CONTENT_TYPE` and `CONTENT_LENGTH` should not be prefixed with `HTTP_`
so we were missing out on them.
> The environment must not contain the keys HTTP_CONTENT_TYPE or
HTTP_CONTENT_LENGTH (use the versions without HTTP_).
This commit manually adds those headers into our list of headers.
Make a request to a configured Rack app and expect to see the content-length and content-type headers show up in Readme dashboard.
=> Send content-type and content-length to Readme

packages/python/readme_metrics/MetricsMiddleware.py
When creating a test app with https://github.com/readmeio/flask-metrics-example, I ran into this error:
```
Traceback (most recent call last):
File "~/flask-starter/venv/lib/python3.7/site-packages/readme_metrics/MetricsMiddleware.py", line 68, in __call__
content_length = int(environ["CONTENT_LENGTH"])
KeyError: 'CONTENT_LENGTH'
```
Per [PEP 3333 definition](https://www.python.org/dev/peps/pep-3333/#id4:~:text=The%20contents%20of%20any%20Content%2DLength%20fields%20in%20the%20HTTP%20request.%20May%20be%20empty%20or%20absent) of `CONTENT_LENGTH`:
> The contents of any `Content-Length` fields in the HTTP request. May be empty or absent.
Set up https://github.com/readmeio/flask-metrics-example and observe the error.
=> fix(python): add fallback in case content-length isn't available

packages/python/readme_metrics/Metrics.py, packages/python/readme_metrics/tests/MetricsMiddleware_test.py
- Required fields appear to have been erroneously removed in [#53](https://github.com/readmeio/metrics-sdks/pull/53). This PR adds back those values.
- Added unit tests to ensure the fields are present
=> Fix: add back fields for package name and metrics api prefix

packages/node/README.md, packages/node/__tests__/index.test.js, packages/node/lib/construct-payload.js
implements readmeio/metrics-sdks#154
https://github.com/readmeio/metrics-sdks/issues/154
Provide access to the response object so that information could be set from `res.locals` or anything else stored in the response.
There were no existing tests for the group options. All other tests are running okay.
=> Add an option to use res in payload

packages/node/README.md, packages/node/__tests__/index.test.js, packages/node/config/default.json, packages/node/index.js, packages/node/package-lock.json, packages/node/package.json
This implements request timeouts in the Node SDK.
Due to some issues with [nock](https://www.npmjs.com/package/nock) `.delay()` not delaying responses as expected, this work is currently untested. The `timeout-signal` approach used here has been verified to be functional though with this code:
```js
const timeoutSignal = require("timeout-signal");
const fetch = require("node-fetch");
fetch('https://httpbin.org/delay/4', { signal: timeoutSignal(3000) }).then((response) => {
console.log(response.status);      
}).catch(error => {
if (error.message === "The user aborted a request.") {
console.log('Request timed out!');
}
})
```
Once the unified testing framework (https://github.com/readmeio/metrics-sdks/pull/90) is merged in, I'll revisit properly testing this work.
=> feat: implementing request timeouts in the node sdk

.github/dependabot.yml
Disabling Dependabot updates on Ruby and Python deps for now until we have someone on the team that can manage those libraries. Right now I've been flying blind on them.
=> ci: disable dependabot on ruby and python deps

packages/node/__tests__/lib/construct-payload.test.js, packages/node/__tests__/lib/process-request.test.js, packages/node/lib/process-request.js
[RM-1405](https://linear.app/readme-io/issue/RM-1405/node) - send a redacted string rather than omitting values for deny/allowlist
Sending a request via the node SDK where a denylist path has been set, should now redact that value, rather than omitting it from the request.
=> feat(node): send a redacted string rather than omitting values

packages/ruby/Gemfile.lock, packages/ruby/lib/readme/filter.rb, packages/ruby/spec/readme/filter_spec.rb, packages/ruby/spec/readme/har/request_serializer_spec.rb, packages/ruby/spec/readme/har/response_serializer_spec.rb, packages/ruby/spec/readme/metrics_spec.rb
[RM-1406](https://linear.app/readme-io/issue/RM-1406/ruby): Redact fields rather than filtering them out
To manually QA, use the Ruby SDK to send a request
=> feat(ruby) redact sensitive fields, rather filter them out entirely

.gitignore, packages/python/README.md, packages/python/readme_metrics/Metrics.py, packages/python/readme_metrics/MetricsApiConfig.py, packages/python/readme_metrics/MetricsMiddleware.py, packages/python/readme_metrics/__init__.py, packages/python/readme_metrics/publisher.py, packages/python/readme_metrics/tests/MetricsMiddleware_test.py, packages/python/readme_metrics/tests/PayloadBuilder_test.py, packages/python/readme_metrics/tests/util_test.py, packages/python/readme_metrics/util.py
This is mostly refactoring, code cleanup, and maintainability improvements, in preparation for larger changes coming later this week.
• Fix RM-1310: Improve our ability to debug the Python SDK by adding a logger and by creating a place to override the Metrics API URL (so ReadMe engineers can test against their local Metrics installation)
• Fix RM-1314: batching prevents the last few requests from reaching our server; the new `atexit_handler` function allows us to flush any remaining logs before the process shuts down.
• Refactored the code for making the ReadMe API post; moved it to its own file.
• Added a timeout parameter for API calls, so that the client doesn't wait forever if the API is unresponsive.
I've also bumped the version to 1.1.0.
Roadmap for changes coming over the next few …
=> Python SDK version 1.1

packages/python/README.md, packages/python/readme_metrics/Metrics.py, packages/python/readme_metrics/MetricsApiConfig.py, packages/python/readme_metrics/MetricsMiddleware.py, packages/python/readme_metrics/PayloadBuilder.py, packages/python/readme_metrics/django.py, packages/python/readme_metrics/flask_readme.py, packages/python/readme_metrics/tests/django_test.py, packages/python/readme_metrics/tests/flask_test.py, packages/python/requirements.txt, packages/python/setup.py
Django and Flask are the two most common frameworks for writing web applications and APIs in Python. Our first Python client was WSGI middleware, which technically worked with both Django and Flask, but its usefulness was rather limited.
When a user integrated their app with our first Python client, the app's `grouping_function` would run in the context of the WSGI middleware, not in the Django or Flask app context. This meant that the grouping function would not have access to any of the data that the app learned about the user while processing the request. For example, if the request contained a session cookie for authentication, the app might have looked up the cookie value in a database, and noted the user account in a request-local variable. But that variable wouldn't be available to …
=> Python Metrics client libraries for Django and Flask

packages/python/README.md, packages/python/readme_metrics/Metrics.py, packages/python/readme_metrics/PayloadBuilder.py, packages/python/readme_metrics/tests/PayloadBuilder_test.py
Give users a clear way to mark requests that shouldn't be logged to ReadMe. A grouping function can return `None` which is an indication that the log should not be captured and sent to ReadMe.
Added documentation to `README.md` and added the functionality to the Metrics core processor.
Added unit tests. Also tested with the metrics-test-python test server, see this commit: https://github.com/readmeio/metrics-test-python/commit/6484c2767fd524237d08352e10082a431d40de8a
=> feat(python): documented way to skip logging a request

packages/python/readme_metrics/MetricsMiddleware.py, packages/python/readme_metrics/__init__.py
My Mac is running in Pacific Time. When I ran our Python test app on my Mac, and it builds a payload for the Metrics API server, it sends local time in the payload's `startedDateTime` field. This is interpreted as UTC time by the API server, so times are displayed incorrectly in the web app.
(I had already addressed this in the Flask and Django adapters; this fix is just for the WSGI middleware implementation.)
This is the last commit for version 2.0, so I'm also bumping the package's version number!
Tested by running metrics-test-python locally.
=> Python metrics client starteddatetime rm 1315

packages/python/readme_metrics/Metrics.py, packages/python/readme_metrics/PayloadBuilder.py, packages/python/readme_metrics/tests/PayloadBuilder_test.py, packages/python/readme_metrics/tests/django_test.py, packages/python/readme_metrics/tests/redaction_test.py
PayloadBuilder now validates the output of the grouping function. If the output isn't a dict or doesn't include `api_key` or `id`, we log an error and don't send the request to ReadMe. If the output is missing other expected fields `email` and `label`, we log a warning but send the request anyway. And if the output includes any unexpected fields, we log a warning and remove them before sending the request to ReadMe.
Note that by default the logger is set to log level `CRITICAL` so users won't typically see these warnings and errors unless they modify the logger in the `MetricsApiConfig` object. I actually think that's fine—we want the metrics clients to be pretty transparent and not pollute our users' logs when they haven't opted in for that.
New unit tests.
=> feat(python): validate and clean up the result of the grouping function

.github/MAINTAINERS.md, packages/python/setup.py
Just docs and a minor fix required to use `setup.py` on my setup (Python 3.9 + setuptools 57.0.0).
=> chore: docs for packaging Python + correct path to Python release version number

packages/ruby/lib/readme/metrics.rb, packages/ruby/spec/readme/metrics_spec.rb
During testing, it can be helpful to see the current user block evaluated
correctly but not actually sent anywhere.
Providing a plain Array as the request queue can be helpful to ensure that
the a request may have been sent.
Providing an object with `push` that is a no-op can be a helpful /dev/null
sink, which permits the middleware to be always present, and not a special
case during testing.
=> feat(ruby): accept custom request queue as option

.husky/commit-msg, package-lock.json, package.json, packages/node/package-lock.json, packages/node/package.json
> ⚠️ This is going to cause some ridiculous merge conflicts in #288 but I can fix those myself.
If after pulling this down and running `npm ci` you can do `npm test`, and tests pass, then this is good.
=> chore(deps-dev): refactor some dev dependencies around

.github/workflows/python.yml
Python 3.10 seems to be causing issues with some of our deps in CI so I'm rolling it back down and pinning to Python 3.7 in CI.
=> ci: pinning the version of python that's used in ci

.github/workflows/php.yml, packages/php/composer.json
PHP 7.3 loses support on the 6th so we're dropping it and also extending our support to PHP 8.1 which was released last month.
https://www.php.net/supported-versions.php
I'm also pinning our dependencies on `vimeo/psalm` and `squizlabs/php_codesniffer` to prevent issues in the future where changes hit their master/main branches that we haven't tested, causing CI failures.
=> feat: dropping support for PHP 7.3, extending support to PHP 8.1

packages/node/__tests__/.eslintrc, packages/node/__tests__/index.test.ts, packages/node/__tests__/lib/process-request.test.ts, packages/node/src/lib/express-middleware.ts, packages/node/src/lib/process-request.ts
- If there is no request body we now delete the key instead of providing null
- Fix urls for nested express objects
See tests
=> fix: remove null postData, add support for nested express routes

packages/ruby/Gemfile.lock, packages/ruby/README.md, packages/ruby/lib/readme/metrics/version.rb
chore: bump ruby sdk version
Gem has been [released](https://rubygems.org/gems/readme-metrics/versions/2.0.0) here
=> chore: bump ruby sdk version

packages/ruby/Gemfile.lock, packages/ruby/readme-metrics.gemspec
Add the uuid gem dependency to the library (by specifying the gem on the `.gemspec`).
Nothing much to test, just require the gem as part of the library.
=> Specify the uuid gem dependency

packages/ruby/Gemfile.lock, packages/ruby/lib/readme/metrics/version.rb, packages/ruby/readme-metrics.gemspec
chore: update gem to 2.0.1 and add os runtime dep
Built and required the gem locally successfully. v2.0.1 has been released.
=> chore: update gem to 2.0.1 and add os runtime dep

packages/node/README.md
It turns out subdomain.readme.com/logs fails, you have to use readme.io. This clarifies that in the docs
=> Minor doc tweak

.github/workflows/nodejs.yml, packages/python/README.md, packages/python/requirements.txt
Also added instructions for setting up a local python environment
https://github.com/psf/black/issues/2964#issuecomment-1080974737
Does CI pass? ✅
=> fix: python CI (upgrade black to 22.3.0) and node CI (pin node.js to 16.14.0)

packages/node/__tests__/lib/process-request.test.ts, packages/node/src/lib/process-request.ts
Some reverse proxies put multiple protocols into x-forwarded-proto
which caused the `new URL()` constructor to fail. I removed the parsed
protocol from the URL constructor, since we're only using that with a
static hostname anyway.
Then in the instance where we do need the parsed protocol, I added some
logic to capture the first protocol if there's more than one.
Fixes: https://github.com/readmeio/metrics-sdks/issues/378
@ilias-t this is my first time editing this code in a while... is this the correct place for this? Or would it make more sense in the fixHeader function: https://github.com/readmeio/metrics-sdks/blob/main/packages/node/src/lib/process-request.ts#L21-L31=
This part in particular feels like it could contain this logic: …
=> fix: x-forwarded-proto header parsing

packages/dotnet/Readme/ConstValues.cs, packages/dotnet/Readme/HarJsonTranslationLogics/ReadmeApiCaller.cs, packages/dotnet/ReadmeMetricsAPI3/Startup.cs, packages/dotnet/ReadmeMetricsAPI3/appsettings.json, packages/dotnet/ReadmeMetricsAPI5/Startup.cs, packages/dotnet/ReadmeMetricsAPI5/appsettings.json, packages/dotnet/ReadmeMetricsAPI6/Program.cs, packages/dotnet/ReadmeMetricsAPI6/ReadmeMetricsAPI6.csproj, packages/dotnet/ReadmeMetricsAPI6/appsettings.json
This is an updated API endpoint, we're deprecating the version-less one.
I've had to manually test this cos there are no automated tests for .net (yet!).
=> fix(dotnet): update SDK to point to /v1/request 

packages/node/__tests__/config.test.ts, packages/node/tsconfig.json
Have to be explicit about this because `include` by default only brings in
JS/TS files:
> If a glob pattern doesn’t include a file extension, then only files with
> supported extensions are included (e.g. .ts, .tsx, and .d.ts by default,
> with .js and .jsx if allowJs is set to true).
https://www.typescriptlang.org/tsconfig#include
I tried to write an automated test for this but couldn't figure out the
best way to do it. In lieu of an automated test, you can run this from the root:
```sh
cd packages/node && npm run build && ls dist/src/config/localhost.json
```
=> fix: ensure all config files are included in the bundled output

packages/node/package-lock.json, packages/node/package.json
| 🚥 Fix RM-XXX |
| :-- |
When using external libraries and their types (such as `'@types/har-format'`), then these have to be added as main "dependencies" instead of "devDependencies" because otherwise clients using your library will get the following error:
> Error: api:test: node_modules/readmeio/dist/src/lib/metrics-log.d.ts(5,26): error TS2307: Cannot find module 'har-format' or its corresponding type declarations.
I tested this in my own TypeScript client code where I am importing your library like this:
> import readmeio from 'readmeio';
If I do it, I am getting **error TS2307**, so I have to install "@types/har-format" manually because its dependencies don't get installed automatically as they are declared as "devDependencies" in your package.
=> fix: add types for libraries used in source code

packages/php/.gitignore, packages/php/composer.json, packages/php/composer.lock
We've been having issues with PHP builds in CI being unstable because we haven't kept `composer.lock` in git. This fixes that!
=> fix: keep composer lock in git

packages/php/src/Metrics.php, packages/php/tests/MetricsTest.php
Noticed this while walking through Metrics earlier today with @gratcliff but our PHP SDK is currently sending metrics to `/request` while all the others are to `/v1/request`.
Here's the PHP test suite running, and failing, locally with the tests still pointing to the `/request` endpoint:
With tests updated to use `/v1/request`:
=> fix: pointing the php sdk at our `/v1/request` endpoint

package-lock.json, packages/node/package-lock.json, packages/node/package.json
This upgrades `multer` to its latest 1.x release to resolve a CVE with a `dicer` subdependency of it.
https://github.com/readmeio/metrics-sdks/security/dependabot/19
`npm audit` no longer reports any vulns:
=> fix: upgrading multer to fix a CVE warning

.github/workflows/nodejs.yml, __tests__/integrations/node.Dockerfile, docker-compose.yml, packages/node/examples/fastify/index.js, packages/node/src/lib/process-response.ts
Building on the work over in #528 - adding fastify to the integration test suite. 
=> feat(integration): add fastify to the integration test suite

.github/MAINTAINERS.md, .github/workflows/split-monorepo.yml, bin/split.sh
Because our PHP SDK is the only package of ours that cannot be published directly from this monorepo we don't need to mirror every SDK out to their own repositories.
After this is merged in I am going to **delete** the following repos:
* https://github.com/readmeio/metrics-sdks-dotnet
* https://github.com/readmeio/metrics-sdks-python
* https://github.com/readmeio/metrics-sdks-ruby
And because our Node SDK used to live at https://github.com/readmeio/metrics and was renamed to `metrics-sdks-node` I am going to **archive** https://github.com/readmeio/metrics-sdks-node.
=> ci: cleaning up our monorepo splitting work to only split up the PHP SDK

.github/workflows/python.yml, packages/python/.pylintrc, packages/python/Makefile, packages/python/examples/flask/app.py, packages/python/readme_metrics/Metrics.py, packages/python/readme_metrics/MetricsApiConfig.py, packages/python/readme_metrics/MetricsMiddleware.py, packages/python/readme_metrics/PayloadBuilder.py, packages/python/readme_metrics/django.py, packages/python/readme_metrics/flask_readme.py, packages/python/readme_metrics/publisher.py, packages/python/readme_metrics/tests/MetricsMiddleware_test.py, packages/python/readme_metrics/tests/PayloadBuilder_test.py, packages/python/readme_metrics/tests/django_test.py, packages/python/readme_metrics/tests/fixtures/Environ.py, packages/python/readme_metrics/tests/flask_test.py, packages/python/readme_metrics/tests/redaction_test.py, packages/python/requirements.txt
| 🚥 Fix RM-5025, #415, #416 |
| :-- |
| | Before | After |
| :--- | :--- | :--- |
| `creator.name` | readme_metrics.PayloadBuilder | readme/metrics (python) |
| `creator.version` | 2.0.1 | 2.0.1 |
| `creator.comment` | 3.8.9 (default, Apr 13 2022, 08:48:06) <br />[Clang 13.1.6 (clang-1316.0.21.2.5)] | arm64-darwin21.3.0/3.8.9 |
All existing tests are/should be still passing.
=> feat(python): HAR consistency and overall cleanup

.alexignore, packages/python/Makefile, packages/python/requirements.dev.txt, packages/python/requirements.txt, packages/python/setup.py
=> feat: splitting out the python dev deps into a separate requirements file

packages/dotnet/README.md
=> fix: nuget rendering of dotnet sdk readme

packages/dotnet/ReadMe/HarJsonTranslationLogics/HarJsonBuilder.cs, packages/dotnet/ReadMe/ReadMe.csproj
| 🚥 Fix RM-5025, #415, #416 |
| :-- |
| | Before | After |
| :--- | :--- | :--- |
| `creator.name` | 	readmeio.net | readme-metrics (dotnet) |
| `creator.version` | 2.0.0 | 2.0.0 |
| `creator.comment` | mac/6.2.9200.0 | x86-win32nt/6.2.9200.0 |
All existing tests are/should be still passing.
=> feat(dotnet): HAR consistency

.github/workflows/dotnet.yml, packages/dotnet/Makefile, packages/dotnet/ReadMe.ruleset, packages/dotnet/ReadMe/ConfigValues.cs, packages/dotnet/ReadMe/ConstValues.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Content.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Cookies.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Creator.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Entries.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Group.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Headers.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Log.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Params.cs, packages/dotnet/ReadMe/HarJsonObjectModels/PostData.cs, packages/dotnet/ReadMe/HarJsonObjectModels/QueryStrings.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Request.cs, packages/dotnet/ReadMe/HarJsonObjectModels/RequestMain.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Response.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Root.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Timing.cs, packages/dotnet/ReadMe/HarJsonTranslationLogics/HarJsonBuilder.cs, packages/dotnet/ReadMe/HarJsonTranslationLogics/ReadmeApiCaller.cs, packages/dotnet/ReadMe/HarJsonTranslationLogics/RequestProcessor.cs, packages/dotnet/ReadMe/HarJsonTranslationLogics/ResponseProcessor.cs, packages/dotnet/ReadMe/Metrics.cs, packages/dotnet/ReadMe/ReadMe.csproj, packages/dotnet/ReadMe/Webhook.cs
| 🚥 Fix #415, #453 |
| :-- |
> ⚠️ There's a fair bit of yakshaving going on here so it'd probably be best to view the diff with whitespace disabled.
All existing tests are/should be still passing.
=> feat(dotnet): overall cleanup

packages/node/Makefile, packages/node/__tests__/lib/construct-payload.test.ts, packages/node/src/lib/construct-payload.ts
| 🚥 Fix RM-5025, #415, #416 |
| :-- |
| | Before | After |
| :--- | :--- | :--- |
| `creator.name` | readmeio | readme-metrics (node) |
| `creator.version` | 5.2.1 | 5.2.1 |
| `creator.comment` | mac/v14.19.3 | x64-darwin21.3.0/14.19.3 |
All existing tests are/should be still passing.
=> feat(node): HAR consistency

packages/sdk-snippets/src/fixtures/webhooks/quirky-escaping.js, packages/sdk-snippets/src/helpers/escape.ts, packages/sdk-snippets/src/targets/__snapshots__/targets.test.ts.snap, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/client.ts, packages/sdk-snippets/src/targets/dotnet/net6/webhooks/fixtures/quirky-escaping.cs, packages/sdk-snippets/src/targets/node/express/webhooks/client.ts, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/quirky-escaping.js, packages/sdk-snippets/src/targets/php/laravel/webhooks/client.ts, packages/sdk-snippets/src/targets/php/laravel/webhooks/fixtures/quirky-escaping.php, packages/sdk-snippets/src/targets/python/flask/webhooks/client.ts, packages/sdk-snippets/src/targets/python/flask/webhooks/fixtures/quirky-escaping.py
This fixes a problem with all of our SDK snippet generators where if any webhook security or server variable had weird characters in either its name or value we might generate a code snippet that wouldn't be parseable by the language in question.
All of these `quirky-escaping` fixtures have been verified to be valid by way of VSCode's intellisense feature. Look mah,  no squigglies.
=> fix(snippets): sanitizing webhook variables before inserting them into code snippets

packages/python/readme_metrics/PayloadBuilder.py, packages/python/readme_metrics/tests/PayloadBuilder_test.py
We were sending post data like this:
```js
{
method: 'POST',
url: 'http://localhost:51141/',
httpVersion: 'HTTP/1.1',
headers: [],
queryString: [],
text: '{"user":{"email":"dom@readme.io"}}',
mimeType: 'application/json'
}
```
When it should be nested inside a `postData` key, like so:
```js
{
method: 'POST',
url: 'http://localhost:51141/',
httpVersion: 'HTTP/1.1',
headers: [],
queryString: [],
postData: {
text: '{"user":{"email":"dom@readme.io"}}',
mimeType: 'application/json'
}
}
```
----
Tbh I didn't know what the ** python syntax did here, but I figured it out
by doing this in the repl:
```
>>> b = { "test": 1 }
>>> { "a": 123, **b }
{'a': 123, 'test': 1}
```
So it appears to be similar to the spread syntax in JS.
=> fix(python): postData wasn't being sent correctly

packages/php/composer.lock, packages/php/examples/laravel/composer.lock
PHP SDK's `examples/laravel` `composer.lock` file had references to the `feat/php-webhooks` branch I was using when was working on that last week. I've re-run `composer update` everywhere to remove that and update any deps that are out of date.
=> chore(deps): running `composer update` in the php sdk

packages/python/examples/metrics_django/metrics/models.py, packages/python/examples/metrics_django/metrics/views.py, packages/python/examples/metrics_django/metrics_django/settings.py, packages/python/readme_metrics/Metrics.py, packages/python/readme_metrics/MetricsApiConfig.py, packages/python/readme_metrics/tests/Metrics_test.py
Previously we were trying to import the grouping function in MetricsApiConfig
which in Django's case gets called from settings.py (before the models have
been setup). So if your grouping function was located in a file that happened
to use a model (or was a function on a model) it would error with the following:
```
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
This PR moves the loading of the grouping function (if it needs to be
imported) into Metrics instead of in the Config, this is late enough for
django to have started so you can use models.
We're having some issues running the python integration tests on CI, so to test this locally you can run:
```sh
make test-python-metrics-django
```
=> fix(python/django): move instantiation of grouping_function 

__tests__/integration-metrics.test.js
We still have the occasionally flaky test in CI so this might help as they most always run fine on the next go around.
https://mochajs.org/#retry-tests
=> test: automatically retry any failed integration tests

packages/sdk-snippets/src/targets/node/express/webhooks/client.ts, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/empty-default.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/empty.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/quirky-escaping.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-and-server-variables.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-types.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-variables.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/server-variables.js
Because our Node SDK snippets use `import` they don't work out of the box on Node without the `NODE_OPTIONS=--experimental-vm-modules` flag.
=> fix: node snippets not working out of the box on node w/o esm compat

Makefile, package-lock.json, package.json, packages/dotnet/ReadMe/HarJsonObjectModels/Content.cs, packages/dotnet/ReadMe/HarJsonObjectModels/Request.cs, packages/dotnet/ReadMe/HarJsonTranslationLogics/RequestProcessor.cs, packages/dotnet/ReadMe/HarJsonTranslationLogics/ResponseProcessor.cs, packages/node/src/lib/object-to-array.ts, packages/node/src/lib/process-request.ts, packages/node/src/lib/process-response.ts, packages/php/src/HAR/Payload.php, packages/php/tests/HAR/PayloadTest.php, packages/php/tests/MetricsTest.php, packages/python/readme_metrics/PayloadBuilder.py, packages/ruby/lib/readme/har/collection.rb, test/helpers/chai-plugins.js, test/integration-metrics.test.js
| 🚥 Fix RM-5036 |
| :-- |
This adds a couple new Chai assertions:
Along with these new assertions I've also fixed some issues in our SDKs that cropped up from it:
* ⚠️ Any HAR with a query string with a non-scalar value will almost certainly crash code snippet generation and Try It execution.
=> feat: adding HAR validation to our integration suite + fixing bugs

packages/sdk-snippets/README.md, packages/sdk-snippets/src/targets/node/express/webhooks/client.ts, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/empty-default.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/empty.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/quirky-escaping.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-and-server-variables.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-types.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/security-variables.js, packages/sdk-snippets/src/targets/node/express/webhooks/fixtures/server-variables.js
| 🚥 Fix RM-5469 |
| :-- |
Per some internal discussion, this updates our Metrics SDK snippet for the Personalized Docs Webhook to print the example server URL to the console once the user starts the server.
In an effort to fast-track this for some launch-related materials, this PR only updates our Node/Express snippet and I've created a ticket for the other snippets in RM-5488.
Does the new snippet look good? And do tests pass?
=> fix(node webhook snippet): add app server link

packages/node/src/lib/process-request.ts, packages/node/test/helpers/chai-plugins.ts, packages/node/test/lib/process-request.test.ts
This fixes a quirk in how our `allowlist` works in the Node SDK where it would redact headers we used to construct the `url` that we set into the HAR for Metrics. Like this:
We're still going to be redacting all non-allowlisted headers by default, we just will do that redaction after we've constructed the URL.
=> fix: quirk where an allowlist would redact HAR URLs

.github/workflows/sync-docs.yml, docs/alternative-methods.md, docs/cloudflare-workers.md, docs/dotnet-setup.md, docs/nodejs-setup.md, docs/php-laravel-setup.md, docs/python-django-setup.md, docs/python-flask-setup.md, docs/python-wsgi-setup.md, docs/ruby-setup.md
We won't know if the syncing works until it's merged into `main`, but a local dry run appears to work fine:
=> fix(docs): update versions/categories

packages/python/readme_metrics/VerifyWebhook.py
| 🚥 Fix https://github.com/readmeio/metrics-sdks/issues/663 |
| :-- |
Fix type error when verifying the webhook request. See https://github.com/readmeio/metrics-sdks/issues/663 for more details.
Here is how I test the code: 
- Link webhook to Readme
- Rebuild and install the fixed python package locally.
- Start the flask server that Readme officially provided.
- Post a request from Readme and verify the request body.
**Screenshot**
=> fix: fix secret type when use hmac func

.github/workflows/php.yml, packages/node/test/index.test.ts, packages/php/composer.json, packages/php/composer.lock, packages/php/examples/laravel/composer.json, packages/php/psalm.xml, test/integrations/php/laravel.Dockerfile
| 🚥 Fixes #31 |
The PHP CI workflow has been updated to run against PHP 8.2 and Laravel 10 so if everything is still passing then this should be g2g.
=> feat(php): supporting laravel 10, php 8.2 + dropping laravel 8

.github/workflows/ruby.yml, packages/ruby/Gemfile.lock, packages/ruby/examples/metrics-rails/Gemfile.lock, packages/ruby/examples/metrics-rails/config/environments/production.rb, packages/ruby/lib/readme/http_request.rb, packages/ruby/readme-metrics.gemspec, packages/ruby/spec/readme/har/request_serializer_spec.rb, packages/ruby/spec/readme/har/response_serializer_spec.rb, packages/ruby/spec/readme/http_request_spec.rb, packages/ruby/spec/readme/metrics_spec.rb, packages/ruby/spec/readme/webhook_spec.rb
Over in #653 we added support for Rack 3, but in doing so we unintentionally removed support for Rails which does not yet support Rack 3. I (slowly) reverted the work in #763 then decided to make this module work with both rack v2 and v3.
We can do this at runtime using a looser runtime dependency in the gemspec: `'rack', '>= 2.2', '< 4'`
https://github.com/readmeio/metrics-sdks/blob/980f92dc50c5cecab167de85681e753b56c1847e/packages/ruby/readme-metrics.gemspec#L30
Then check for the version at runtime using `Gem.loaded_specs['rack'].version > Gem::Version.create('3.0')`
https://github.com/readmeio/metrics-sdks/blob/980f92dc50c5cecab167de85681e753b56c1847e/packages/ruby/lib/readme/http_request.rb#L9
I had to add a bunch of conditionals both in the code and tests to make this work, i'm sure …
=> feat: dynamically support rack v2 and v3

packages/node/src/lib/metrics-log.ts, packages/node/test/index.test.ts
Some metrics users are sending invalid traffic (like with an invalid API key) at a rate of tens or even hundreds of requests per second. This change updates the metrics client to pay attention to the HTTP response's status code as sent from the metrics server. If it receives an HTTP error, this stops sending logs for 15 seconds to avoid bombarding our server with bad requests. Only certain errors trigger a backoff; they're documented in the code.
1. **Why 15 seconds?** That's enough to dramatically reduce the amount of invalid traffic coming to the server. It's short enough that the client will recover quickly if it pauses due to a server error, like a one-off HTTP 500.
2. **Do we buffer the requests and try again?** No. For HTTP 401/403/429 there's essentially no way for the client to …
=> feat: backoff requests to the ReadMe server after certain HTTP responses

packages/cloudflare-worker/src/index.js
Sets the user-agent when the Cloudflare worker POSTs to the ReadMe metrics API.
It's not urgent we get this out, but I'm not familiar with how to release this.
=> chore(cloudflare-worker): set User-Agent on POSTs to ReadMe Metrics API

Makefile, test/integration-metrics.test.js
**_Cherrypicked this commit from #653, seeing if it fixes flaky integration tests_**
OK here's where this PR gets interesting... I spent a bunch of time debugging the test failures here: https://github.com/readmeio/metrics-sdks/pull/653#pullrequestreview-1309362560
I eventually settled on some code that was working, committed here: 224e2ad54c9bef641db39e650bfdc464a55c929b
But that was causing a bunch of `EOFErrors` from Ruby when sending the HTTP request out to the metrics server:
```
#<Thread:0x000000010c67e488 /Users/domh/Sites/readmeio/metrics-sdks/packages/ruby/lib/readme/request_queue.rb:30 run> terminated with exception (report_on_exception is true):
/opt/homebrew/lib/ruby/gems/3.1.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:227:in `rbuf_fill': end of file reached (EOFError)
from …
```
=> fix: remove `HAS_HTTP_QUIRKS` flag from integration tests

.github/workflows/python.yml, packages/python/readme_metrics/PayloadBuilder.py
`os.uname()` is not available on all builds of Python[^1]. We're using this to generate the `creator.comment` field in our payloads to the Metrics API so as long as we get an *approximate* release version, which is apparently available with `platform.uname()`[^2], that should be good enough.  
I'm also expanding our Python unit test suite to run on Windows. I would like to also run our framework integration suite on Windows but that isn't going to be possible without some major overhauls to our Docker system that that utilzes. 
[^1]: https://docs.python.org/3.8/library/os.html#os.uname
[^2]: It falls back to an empty string if not available so it shouldn't break anything. https://docs.python.org/3.8/library/platform.html#platform.uname
=> fix(python): dont use `os.uname()`

.github/workflows/python.yml, packages/python/.pylintrc, packages/python/requirements.dev.txt
| 🚥 Fixes ISSUE_ID |
- upgrade pylint
- re-enable python 3.11 tests
fixes issue reported on #847 [here](https://github.com/readmeio/metrics-sdks/pull/847#discussion_r1236021464)
- I reproduced the problem locally in a virtualenv, upgraded pylint, and it went away
=> chore: upgrade pylint and reenable 3.11

packages/node/src/lib/process-request.ts, packages/node/test/lib/process-request.test.ts
| 🚥 Resolves #883 |
We were wrongly assuming that POST bodies will always be set for `application/x-www-form-urlencoded` requests. This fixes that!
=> fix(node): TypeError when parsing empty POST body

packages/python/examples/metrics_django/metrics_django/settings.py, packages/python/readme_metrics/GetProjectBaseUrl.py, packages/python/readme_metrics/Metrics.py, packages/python/readme_metrics/MetricsApiConfig.py, packages/python/readme_metrics/PayloadBuilder.py, packages/python/readme_metrics/tests/GetProjectBaseUrl_test.py, packages/python/readme_metrics/tests/Metrics_test.py, packages/python/readme_metrics/tests/PayloadBuilder_test.py, test/integration-metrics.test.js
Adding support in Python for a new configuration option, `base_log_url` (e.g. "docs.example.com"), which is consumed to append a new response header, `x-documentation-url` (e.g. "docs.example.com/logs/${UUID}").  
This configuration option is supported across all other SDKs, accept for Ruby, currently. It's used both to generate a direct link to the log that ReadMe's metrics SDK has just captured, as well as to prevent double log insertion when a request is made via "Try-It" in a documentation site.
=> fix(python): x-doc-url support wip

packages/php/src/Metrics.php
| 🚥 Resolves #943 |
The composer config is only used to cache the `base_log_url`. If the `open_basedir` can't be changed within the php.ini configuration (like for [serversideup docker images](https://hub.docker.com/r/serversideup/php)) the package can't be used.
I've tested the changes with my own and the example application.
=> fix(php): open_basedir restriction

Makefile, packages/ruby/lib/readme/http_request.rb, packages/ruby/lib/readme/mask.rb, packages/ruby/lib/readme/payload.rb, packages/ruby/spec/readme/http_request_spec.rb, packages/ruby/spec/readme/payload_spec.rb
| 🚥 Resolves CX-674 |
Masks the `Authorization` header and API keys sent via the Ruby Rack middleware.
Added automated tests to verify the sensitive data gets hashed properly and matches the same expected output as the Node.js app
=> (feat) Add hashing of sensitive data to the Ruby gem

.github/workflows/lint-pr-title.yml, .husky/commit-msg, package-lock.json, package.json
Lints PR titles so our release generation works properly! This feels like a more robust check than husky, so I removed that as well.
Confirmed locally that the VSCode GitHub Actions extension likes this ✅
=> ci: lint PR titles, removes husky

packages/ruby/Gemfile.lock, packages/ruby/lib/readme/metrics/version.rb, packages/ruby/lib/readme/payload.rb, packages/ruby/spec/readme/metrics_spec.rb, packages/ruby/spec/readme/payload_spec.rb
Add the `_version` parameter to the payload so the server does not process the headers.
Updated a test to ensure the `_version` parameter is on the payload request.
=> fix(ruby): Add `_version`

packages/node/src/lib/ReadMe.ts, packages/node/test/index.test.ts
This updates the SDK to be a class. As part of this, the signature is slightly updated:
```diff
import { ReadMe } from 'readmeio';
- const readme = ReadMe(key);
+ const readme = new ReadMe(key);
app.use(readme.express(() => {}));
```
Strongly suggest hiding whitespace before reviewing! Does this signature look good? Do tests still pass?
=> refactor: convert `ReadMe` into a class

packages/node/src/lib/ReadMe.ts, packages/node/src/lib/get-group-id.ts, packages/node/test/lib/get-group-id.test.ts
With the unified snippet work we weren't properly getting the label from the keys array. This makes getGroupIdByApiKey more generic to return the label as well.
=> fix: properly send label with unified snippet

.github/workflows/ruby.yml
We're running `bundle update` in our Ruby CI before running unit tests and this is upgrading all of our dependencies. Our usage of some of these dependencies apparently needs some work as every Ruby unit test fails on these updated deps.
=> ci(ruby): don't run `bundle update`

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.md
Taking inspiration from AVA's [issue creation screen](https://github.com/avajs/ava/issues/new/choose), this adds some new issue templates for folks to use.
=> feat: creating issue templates

package-lock.json, packages/node/package.json, packages/node/src/lib/construct-payload.ts, packages/node/src/lib/log.ts, packages/node/src/lib/metrics-log.ts
Removing `uuid` dep. We should be able to use `node:crypto` for any UUID generation going forward.
=> chore(uuid): deprecate `uuid` package in favor of `node:crypto`

.github/workflows/dotnet.yml, .github/workflows/nodejs.yml, .github/workflows/php.yml, .github/workflows/python.yml, .github/workflows/ruby.yml, docker-compose.yml, package-lock.json, package.json, test/integration-metrics.test.js, test/integration-webhooks.test.js
Moves out integration test suite off an outdated collection of `isomorphic-fetch`, `form-data-encoder`, and `formdata-node` in favor of native `fetch` and `FormData` utilizations.
=> feat: moving our integration test suite over to using native fetch

.github/workflows/dotnet.yml, .github/workflows/nodejs.yml, .github/workflows/php.yml, .github/workflows/python.yml, .github/workflows/ruby.yml, Makefile
Docker compose v1 was removed from runner-images, and this caused some workflow jobs to fail
=> fix(integration-tests): update docker compose syntax

package-lock.json, packages/node/package.json, packages/node/src/lib/ReadMe.ts, packages/node/src/lib/console-logger.ts, packages/node/src/lib/construct-payload.ts, packages/node/src/lib/get-project-base-url.ts, packages/node/src/lib/log.ts, packages/node/src/lib/logger.ts, packages/node/src/lib/metrics-log.ts, packages/node/src/lib/pino-logger.ts, packages/node/src/lib/process-request.ts, packages/node/test/index.test.ts, packages/node/test/lib/console-logger.test.ts, packages/node/test/lib/logger.test.ts
| 🚥 Resolves #1045 |
Implementation of the Node.js console logger for trace, debug and error logs.
Implemented as a singleton class to make sure that its instance is the only one in the Node.js SDK. It has a config that allows you to customize the log prefix or disable the logging option, by default logging option is set to disabled and prefix is "[readmeio]". It has 3 main methods: trace, debug and errors. They can be called anywhere in the code. You need to import the logger instance from the "logger.ts" file and call the required method (logger.error(...) and so on). It takes the following fields in the object as a parameter: 
- message (required)
- args (optional)
- err (only for logger.error)
Set "logger" option in options object to true and try to send a …
=> feat(node): pluggable logging class

packages/dotnet/ReadMe/Metrics.cs, packages/node/src/lib/log.ts, packages/node/test/lib/log.test.ts, packages/php/src/Metrics.php, packages/php/tests/MetricsTest.php, packages/python/readme_metrics/django.py, packages/python/readme_metrics/flask_readme.py, packages/python/readme_metrics/tests/django_test.py, packages/python/readme_metrics/tests/flask_test.py
| 🚥 Resolves #58  |
Add a middleware checks for skipping OPTIONS requests
=> feat(dotnet, node, php, python): exclude OPTIONS requests from being logged

packages/python/readme_metrics/VerifyWebhook.py
The function checks if it's None, so the type hinting should accept None
I didn't create an issue for this, but I can if that helps.
Update the type hinting on VerifyWebhook to accurately reflect what the function can accept. In my application code, I call `signature` with a variable that can be a `str` or  `None`, and mypy is flagging that as a problem because the function says it only accepts `str`.
No testing required, since it's just a type hinting change.
I chose to use `typing.Optional[str]` instead of `str | None` because that works on more versions of python.
=> chore(python): Update type hinting on VerifyWebhook's signature

.github/MAINTAINERS.md, packages/kong-plugin/.busted, packages/kong-plugin/.editorconfig, packages/kong-plugin/.gitignore, packages/kong-plugin/.luacheckrc, packages/kong-plugin/.luacov, packages/kong-plugin/.pongo/pongorc, packages/kong-plugin/Dockerfile, packages/kong-plugin/README.md, packages/kong-plugin/kong/plugins/readme-plugin/handler.lua, packages/kong-plugin/kong/plugins/readme-plugin/schema.lua, packages/kong-plugin/spec/readme-plugin/01-integration_spec.lua
Add kong plugin
Follow the "Deploying locally" instructions in the PR
=> feat: kong plugin

.github/workflows/python.yml
Remove Python 3.8 from Github workflow since it is deprecated (EOL).
=> chore(python): remove support for Python 3.8 (EOL)

.github/MAINTAINERS.md, packages/dotnet/ReadMe/ConstValues.cs, packages/dotnet/ReadMe/ReadMe.csproj
Version bump of the .Net package and updates Maintainers.md with additional details and updated steps.
=> chore(dotnet): bump dotnet to 2.2.0 and updates maintainer readme

packages/python/readme_metrics/PayloadBuilder.py
Fix prefix path not captured issue.
We had a problem with FastAPI integration that the Middleware did not captured the path for each request and sent only “/” instead. 
Try sending a few test requests with paths, for example, “/hello/world”. Now it should not be empty.
=> fix(python/fastapi): prefix path capturing

packages/python/readme_metrics/django.py, packages/python/readme_metrics/fastapi.py, packages/python/readme_metrics/flask_readme.py
Add a handler to ignore middleware when we have an empty groupingFn (grouping_function is None).
Try sending test requests with grouping function that returns None. 
In this case, the middleware should be ignored.
=> fix(python): ignore the middleware when groupingFn is None

packages/python/readme_metrics/fastapi.py
Small fix for a groupingFn exception handling (just to make sure app is not crashing)
=> fix(python/fastapi): empty groupingFn exception handling
